// main.dart
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:workmanager/workmanager.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
// import 'firebase_options.dart'; // TODO: Uncomment this after running 'flutterfire configure'

import 'app.dart';
import 'services/notification_service.dart';
import 'core/utils/date_formatter.dart';

/// Top-level FCM Background Message Handler - SV
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // TODO: Uncomment options when firebase_options.dart is generated by FlutterFire
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await Firebase.initializeApp(); 
  
  await NotificationService().init();
  
  final data = message.data;
  final title = data['title'] ?? message.notification?.title ?? 'Amai Yuki';
  final body = data['body'] ?? message.notification?.body ?? 'New message received!';
  
  await NotificationService().showNotification(
    id: DateTime.now().millisecondsSinceEpoch.remainder(100000),
    title: title,
    body: body,
    payload: jsonEncode(data),
  );
}

/// Top-level or static function representing the entrypoint for Workmanager background tasks.
/// Must be annotated with @pragma('vm:entry-point') so the compilation tree doesn't strip it. - SV
@pragma('vm:entry-point')
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    // 1. Ensure Flutter framework communication bounds are bound to the native engine isolate. - SV
    WidgetsFlutterBinding.ensureInitialized();

    // 2. Open preferences and locate existing authentication session token. - SV
    final prefs = await SharedPreferences.getInstance();
    final token = prefs.getString('auth_token');

    // If the user isn't logged in, there's no chat session to poll. Silent exit. - SV
    if (token == null || token.isEmpty) {
      return Future.value(true);
    }

    try {
      // 3. Make a direct, high-performance REST call to fetch active user conversations. - SV
      final res = await http.get(
        Uri.parse('https://yukiamai.pythonanywhere.com/direct/conversations'),
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json',
          'Authorization': 'Bearer $token',
        },
      );

      if (res.statusCode == 200) {
        final Map<String, dynamic> body = jsonDecode(res.body);
        if (body['success'] == true && body['data'] != null) {
          final List<dynamic> conversations = body['data']['conversations'] ?? [];

          // Initialize notification engine inside this background isolate. - SV
          await NotificationService().init();

          for (var convoJson in conversations) {
            final int unreadCount = convoJson['unread_count'] as int? ?? 0;

            if (unreadCount > 0) {
              final String otherUserId = (convoJson['other_user_id'] ?? convoJson['user_id'])?.toString() ?? '';
              final String otherUsername = (convoJson['other_username'] ?? convoJson['username'])?.toString() ?? '';
              final String? otherUserFullName = convoJson['full_name']?.toString();
              final String lastMessage = convoJson['last_message']?.toString() ?? '';
              final String timestampStr = convoJson['timestamp']?.toString() ?? '';

              // Unique key to track if we've already push-notified this specific message signature.
              // Prevents annoying duplicate status bar alerts on repeat polling runs. - SV
              final String cacheKey = 'last_notified_msg_$otherUserId';
              final String? lastNotifiedMsg = prefs.getString(cacheKey);
              final String currentMsgSig = '$lastMessage|$timestampStr';

              if (lastNotifiedMsg != currentMsgSig) {
                // Encode the payload JSON so tapping the notification triggers deep link navigation. - SV
                final payload = jsonEncode({
                  'otherUserId': otherUserId,
                  'otherUsername': otherUsername,
                  'otherUserFullName': otherUserFullName,
                });

                await NotificationService().showNotification(
                  id: otherUserId.hashCode,
                  title: otherUserFullName ?? otherUsername,
                  body: lastMessage,
                  payload: payload,
                );

                // Persist the message signature to cache to avoid duplicate alerts. - SV
                await prefs.setString(cacheKey, currentMsgSig);
              }
            }
          }
        }
      }
    } catch (e) {
      debugPrint('DEBUG: Background thread notification polling failure: $e');
    }

    return Future.value(true);
  });
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent, 
    statusBarIconBrightness: Brightness.light,
  ));
  
  // Initialize notification settings for the main thread. - SV
  await NotificationService().init();

  // Fetch client & server timezone offsets dynamically via IP lookup to handle clock/timezone discrepancies. - SV
  DateFormatter.initializeTimezonesFromIp();

  // Initialize the Workmanager background task scheduler. - SV
  try {
    await Workmanager().initialize(
      callbackDispatcher,
      isInDebugMode: false,
    );

    // Register a periodic task running every 15 minutes (OS minimum limit).
    // This allows the app to fetch direct messages even when terminated/killed! - SV
    await Workmanager().registerPeriodicTask(
      'direct_messages_periodic_polling',
      'fetch_direct_messages_task',
      frequency: const Duration(minutes: 15),
      existingWorkPolicy: ExistingPeriodicWorkPolicy.keep, // Updated for workmanager 0.9.0 which separates periodic and one-off policies. - SV
      constraints: Constraints(
        networkType: NetworkType.connected,
      ),
    );
  } catch (e) {
    debugPrint('DEBUG: Failed to register background Workmanager task: $e');
  }
  // --- FCM Real-Time Push Setup --- SV
  try {
    // TODO: Uncomment options when firebase_options.dart is generated by FlutterFire
    // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    await Firebase.initializeApp();
    
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    
    final messaging = FirebaseMessaging.instance;
    await messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );
    
    FirebaseMessaging.onMessage.listen((RemoteMessage message) async {
      final data = message.data;
      final title = data['title'] ?? message.notification?.title ?? 'Amai Yuki';
      final body = data['body'] ?? message.notification?.body ?? 'New message received!';
      
      await NotificationService().showNotification(
        id: DateTime.now().millisecondsSinceEpoch.remainder(100000),
        title: title,
        body: body,
        payload: jsonEncode(data),
      );
    });
    
    final token = await messaging.getToken();
    if (token != null) {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('fcm_token', token);
      debugPrint('DEBUG: FCM Token generated: $token');
    }
  } catch (e) {
    debugPrint('DEBUG: Firebase initialization failed: $e');
  }
  
  runApp(const AmaiYukiApp());
}
